version '2'
services:
  nexus:
    build: ./ci/nexus
    ports:
      - "8081:8081"
  jenkins:
    build: ./ci
    ports:
      - "8090:8080"
    volumes_from:
      - jenkinsdata
  jenkinsdata:
    build: jenkins-data
