# Note, you need to set sudo sysctl -w vm.max_map_count=262144
# for running elk on linux
version: '2'
services:
  proposal:
    image: latetuna/proposal:latest
    links:
      - kafka
#    environment:
#      VIRTUAL_HOST: "*:4000/proposal"
    ports:
      - "8090:8080"
  conference:
    image: latetuna/conference:latest
    links:
      - kafka
    ports:
      - "8091:8080"
#    environment:
#      VIRTUAL_HOST: "*:4000/conference"
  gui:
    build: ./gui
    ports:
      - "3000:3000"
      - "8088:8088"
    links:
      - proposal
      - conference
      - elk
    environment:
      HOT_RELOAD_PORT: 8100
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: ./eventbus
    ports:
      - "9092:9092"
    links:
      - zookeeper:zk
    environment:
      # Note: Non-Linux users must set this
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DELETE_TOPIC_ENABLED: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data_kafka:/kafka
  elk:
    image: sebp/elk
    ports:
    - "5601:5601"
    - "5044:5044"
#  lb:
#    image: dockercloud/haproxy
#    depends_on:
#      - proposal
#      - conference
#    links:
#      - conference
#      - proposal
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    ports:
#      - "4000:80"
#      - "1936:1936"
