version: '2'
services:
  proposal:
    image: latetuna/proposal:latest
    links:
      - kafka
  conference:
    image: latetuna/conference:latest
    links:
      - kafka
  gui:
    build: ./gui
    ports:
      - "3000:3000"
      - "8088:8088"
    links:
      - proposal
      - conference
    environment:
      HOT_RELOAD_PORT: 8100
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: ./eventbus
    ports:
      - "9092:9092"
    links:
      - zookeeper:zk
    environment:
      # Note: Non-Linux users must set this
      KAFKA_ADVERTISED_HOST_NAME:
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data_kafka:/kafka
