# Developer overrides, included by defualt by Docker. Mounts local gradle
# cache to avoid multiple downloads.

proposal:
  volumes:
    - ~/.gradle:/.gradle
  environment:
    MAVEN_LOCAL: "true"
conference:
  volumes:
    - ~/.gradle:/.gradle
  environment:
    MAVEN_LOCAL": "true"
