# Note, you need to set sudo sysctl -w vm.max_map_count=262144
# for running elk on linux
version: '2'
services:
  proposal:
    image: latetuna/proposal:latest
    links:
      - kafka
#    environment:
#      VIRTUAL_HOST: "*:4000/proposal, */"
    ports:
      - "8090:8090"
  conference:
    image: latetuna/conference:latest
    links:
      - kafka
    ports:
      - "8091:8091"
#    environment:
#      VIRTUAL_HOST: "*:4000/conference, */"
  gui:
    build: ./gui
    ports:
      - "3000:3000"
      - "8088:8088"
    links:
      - proposal
      - conference
      - elk
    environment:
      HOT_RELOAD_PORT: 8100
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: ./eventbus
    ports:
      - "9092:9092"
    links:
      - zookeeper:zk
    environment:
      # For now it is not possible to run services within docker and IDE, you
      # have to choose either.
      #
      # Use this line when starting services from IDE
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      # Use this line when running the services with docker
      #KAFKA_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CREATE_TOPICS: "si.topic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_DELETE_TOPIC_ENABLED: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data_kafka:/kafka
  elk:
    image: sebp/elk
    ports:
    - "5601:5601"
    - "5044:5044"
#  lb:
#    image: dockercloud/haproxy
#    depends_on:
#      - proposal
#      - conference
#    links:
#      - conference
#      - proposal
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    ports:
#      - "4000:80"
#      - "1936:1936"
